### ISSUE TITLE
I can reach other dir's file

### ISSUE THREAD

**Issue by karunland** [msaistaken/msaistaken.github.io#1]
I can cat proficient.txt and familiar.txt even though I am not in the same dir.
ASAP fix.🥰 :D

**Comment by imsakg** [comment]
_Hey,_
I'm a guy who exports the paths that he needs to access via **$PATH**. So that's just how I designed it. This not a bug or problem (atleast just for me).  BTW, this repository is a dead since I built my own [website](https://msakg.com/). Anyway, you can send PR requests, I'd be happy to review them. ^^
